...
import { CustomIconsModule } from 'ionic2-custom-icons';
...
@NgModule({
  ...
  imports: 
    IonicPageModule.forChild(BookmarkPage),
    CustomIconsModule //Add this!
  ]
  ...

export class BookmarkPageModule {}